/* 
 * Problem 2: Even Fibonacci Numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 */
#include<stdio.h>

int fib(int);


int main() {
  unsigned long n;

  scanf("%ul", &n);
  printf("Fibonacci series\n");

  for (int c = 1; c <= n; c++)
  {
    printf("%d\n", fib(c));
  }

  return 0;
}


int fib(int n) {
  if (n == 0)
    return 0;
  else if (n == 1)
    return 1;
  else
    return ( fib(n-1) + fib(n-2) );
}

