# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
fibonacci_list = [1]


def fib(n):
    global fibonacci_list
    a, b = 1, 1
    for i in range(n - 1):
        a, b = b, a + b
        if not b in fibonacci_list:
            fibonacci_list.append(b)
    return a


def sum_of_even_values(value_list):
    sums = 0
    for i in value_list:
        if i % 2 == 0:
            sums += i
    return sums


if __name__ == '__main__':
    num = 1
    while fib(num) < 4000000:
        num += 1

    a = sum_of_even_values(fibonacci_list)
    print a

